version: '2'
services:
  zookeeper:
    container_name: Zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - custom
  kafka:
    container_name: Kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.107.153
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - custom

networks:
  custom:
    external: true
